import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { createGenerator } from "ts-json-schema-generator";

const root = resolve(import.meta.dirname, "..");
const jsonPath = resolve(root, "openapi", "drama-watch.openapi.json");
const modulePath = resolve(root, "src", "contracts", "generated-openapi.ts");
const check = process.argv.includes("--check");

const schema = createGenerator({
  path: resolve(root, "src", "contracts", "public-api.contract.ts"),
  tsconfig: resolve(root, "tsconfig.json"),
  type: "PublicApiContract",
  expose: "export",
  additionalProperties: false,
  jsDoc: "extended",
}).createSchema("PublicApiContract");

const schemas = rewriteReferences(schema.definitions ?? {});
const document = {
  openapi: "3.1.0",
  info: {
    title: "Drama Watch API",
    version: "1.0.0",
    description:
      "Public request and response contract generated from the NestJS API types.",
  },
  servers: [{ url: "/api" }],
  security: [{ sessionCookie: [] }],
  paths: createPaths(),
  components: {
    securitySchemes: {
      sessionCookie: {
        type: "apiKey",
        in: "cookie",
        name: "better-auth.session_token",
      },
    },
    schemas,
  },
};

const json = `${JSON.stringify(document, null, 2)}\n`;
const module = `// Generated by scripts/generate-openapi.mjs. Do not edit.\n\nexport const OPENAPI_DOCUMENT = ${JSON.stringify(document, null, 2)} as const;\n`;

if (check) {
  await assertCurrent(jsonPath, json);
  await assertCurrent(modulePath, module);
  console.log("OpenAPI contract is current.");
} else {
  await writeFile(jsonPath, json, "utf8");
  await writeFile(modulePath, module, "utf8");
  console.log(`Generated ${jsonPath}`);
}

function rewriteReferences(value) {
  if (Array.isArray(value)) {
    return value.map(rewriteReferences);
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .filter(([key]) => key !== "$schema")
        .map(([key, item]) => [
          key,
          key === "$ref" && typeof item === "string"
            ? item.replace("#/definitions/", "#/components/schemas/")
            : rewriteReferences(item),
        ]),
    );
  }

  return value;
}

async function assertCurrent(path, expected) {
  let actual;
  try {
    actual = await readFile(path, "utf8");
  } catch {
    throw new Error(`${path} is missing. Run npm run contracts:generate.`);
  }

  if (actual !== expected) {
    throw new Error(`${path} is stale. Run npm run contracts:generate.`);
  }
}

function createPaths() {
  const ref = (name) => ({ $ref: `#/components/schemas/${name}` });
  const array = (name) => ({ type: "array", items: ref(name) });
  const jsonResponse = (schema, description = "Successful response") => ({
    description,
    content: { "application/json": { schema } },
  });
  const body = (name) => ({
    required: true,
    content: { "application/json": { schema: ref(name) } },
  });
  const operation = ({
    id,
    tag,
    response,
    request,
    status = "200",
    anonymous = false,
  }) => ({
    operationId: id,
    tags: [tag],
    ...(anonymous ? { security: [] } : {}),
    ...(request ? { requestBody: body(request) } : {}),
    responses: {
      [status]:
        status === "204"
          ? { description: "No content" }
          : jsonResponse(response),
    },
  });

  const paths = {
    "/search": {
      get: operation({ id: "searchMedia", tag: "Media", response: ref("MediaSearchResponse") }),
    },
    "/media/{mediaType}/{tmdbId}": {
      get: operation({ id: "getMediaDetails", tag: "Media", response: ref("MediaDetails") }),
    },
    "/media/{mediaType}/{tmdbId}/refresh": {
      post: operation({ id: "refreshMediaDetails", tag: "Media", response: ref("MediaDetails") }),
    },
    "/media/{mediaType}/{tmdbId}/friend-context": {
      get: operation({ id: "getMediaFriendContext", tag: "Friends", response: ref("MediaFriendContextResponse") }),
    },
    "/library": {
      get: operation({ id: "listLibrary", tag: "Library", response: array("LibraryEntryResponse") }),
      post: operation({ id: "addLibraryEntry", tag: "Library", request: "AddLibraryEntryDto", response: ref("LibraryEntryResponse"), status: "201" }),
    },
    "/library/{entryId}": {
      get: operation({ id: "getLibraryEntry", tag: "Library", response: ref("LibraryEntryResponse") }),
      patch: operation({ id: "updateLibraryEntry", tag: "Library", request: "UpdateLibraryEntryDto", response: ref("LibraryEntryResponse") }),
      delete: operation({ id: "deleteLibraryEntry", tag: "Library", status: "204" }),
    },
    "/library/{entryId}/status": {
      patch: operation({ id: "updateLibraryStatus", tag: "Library", request: "UpdateLibraryStatusDto", response: ref("LibraryEntryResponse") }),
    },
    "/library/{entryId}/progress": {
      patch: operation({ id: "updateLibraryProgress", tag: "Library", request: "UpdateProgressDto", response: ref("LibraryEntryResponse") }),
    },
    "/library/{entryId}/rating": {
      patch: operation({ id: "updateLibraryRating", tag: "Library", request: "UpdateRatingDto", response: ref("LibraryEntryResponse") }),
    },
    "/library/{entryId}/playback-preference": {
      patch: operation({ id: "updateLibraryPlaybackPreference", tag: "Library", request: "UpdatePlaybackPreferenceDto", response: ref("LibraryEntryResponse") }),
    },
    "/statistics": {
      get: operation({ id: "getStatistics", tag: "Statistics", response: ref("StatisticsOverviewResponse") }),
    },
    "/telegram/connection": {
      get: operation({ id: "getTelegramConnection", tag: "Telegram", response: ref("TelegramConnectionResponse") }),
      delete: operation({ id: "disconnectTelegram", tag: "Telegram", status: "204" }),
    },
    "/telegram/link": {
      post: operation({ id: "createTelegramLink", tag: "Telegram", response: ref("TelegramLinkResponse"), status: "201" }),
    },
    "/friends": {
      get: operation({ id: "listFriends", tag: "Friends", response: ref("FriendshipsResponse") }),
    },
    "/friends/request": {
      post: operation({ id: "requestFriend", tag: "Friends", request: "CreateFriendRequestDto", response: ref("FriendshipResponse"), status: "201" }),
    },
    "/friends/{friendshipId}/accept": {
      post: operation({ id: "acceptFriendRequest", tag: "Friends", response: ref("FriendshipResponse") }),
    },
    "/friends/{friendshipId}/reject": {
      post: operation({ id: "rejectFriendRequest", tag: "Friends", status: "204" }),
    },
    "/friends/{friendshipId}": {
      delete: operation({ id: "deleteFriendship", tag: "Friends", status: "204" }),
    },
    "/suggestions": {
      get: operation({ id: "listSuggestions", tag: "Suggestions", response: ref("SuggestionsResponse") }),
      post: operation({ id: "createSuggestion", tag: "Suggestions", request: "CreateSuggestionDto", response: ref("SuggestionResponse"), status: "201" }),
    },
    "/suggestions/{suggestionId}/accept": {
      post: operation({ id: "acceptSuggestion", tag: "Suggestions", response: ref("SuggestionResponse") }),
    },
    "/suggestions/{suggestionId}/dismiss": {
      post: operation({ id: "dismissSuggestion", tag: "Suggestions", response: ref("SuggestionResponse") }),
    },
    ...resourcePaths({
      base: "/lists",
      tag: "Shared lists",
      singular: "SharedList",
      createRequest: "CreateSharedListDto",
      updateRequest: "UpdateSharedListDto",
      listResponse: array("SharedListResponse"),
      detailsResponse: ref("SharedListDetailsResponse"),
    }),
    "/lists/{listId}/invites": {
      get: operation({ id: "listSharedListInvites", tag: "Shared lists", response: array("SharedListPendingInviteResponse") }),
      post: operation({ id: "createSharedListInvite", tag: "Shared lists", request: "CreateSharedListInviteDto", response: ref("SharedListInviteResponse"), status: "201" }),
    },
    "/lists/{listId}/invites/{inviteId}": {
      delete: operation({ id: "revokeSharedListInvite", tag: "Shared lists", status: "204" }),
    },
    "/lists/{listId}/members/{memberUserId}": {
      patch: operation({ id: "updateSharedListMember", tag: "Shared lists", request: "UpdateSharedListMemberDto", response: ref("SharedListMemberResponse") }),
      delete: operation({ id: "removeSharedListMember", tag: "Shared lists", status: "204" }),
    },
    "/lists/{listId}/items": {
      post: operation({ id: "addSharedListItem", tag: "Shared lists", request: "AddSharedListItemDto", response: ref("SharedListItemResponse"), status: "201" }),
    },
    "/lists/{listId}/items/{itemId}": {
      patch: operation({ id: "updateSharedListItem", tag: "Shared lists", request: "UpdateSharedListItemDto", response: ref("SharedListItemResponse") }),
      delete: operation({ id: "deleteSharedListItem", tag: "Shared lists", status: "204" }),
    },
    "/lists/{listId}/reorder": {
      post: operation({ id: "reorderSharedListItems", tag: "Shared lists", request: "ReorderSharedListItemsDto", response: array("SharedListItemResponse"), status: "201" }),
    },
    "/list-invites/{identifier}/accept": {
      post: operation({ id: "acceptSharedListInvite", tag: "Shared lists", response: ref("SharedListDetailsResponse"), status: "201" }),
    },
    "/public/lists": {
      get: operation({ id: "discoverPublicLists", tag: "Shared lists", response: ref("PublicSharedListDiscoveryResponse"), anonymous: true }),
    },
    "/public/lists/{publicSlug}": {
      get: operation({ id: "getPublicSharedList", tag: "Shared lists", response: ref("PublicSharedListDetailsResponse"), anonymous: true }),
    },
    ...resourcePaths({
      base: "/wheels",
      tag: "Wheels",
      singular: "Wheel",
      createRequest: "CreateWheelDto",
      updateRequest: "UpdateWheelDto",
      listResponse: array("WheelResponse"),
      detailsResponse: ref("WheelDetailsResponse"),
    }),
    "/wheels/{wheelId}/spin": {
      post: operation({ id: "spinWheel", tag: "Wheels", response: ref("WheelSpinResponse"), status: "201" }),
    },
    "/wheels/{wheelId}/history": {
      get: operation({ id: "getWheelHistory", tag: "Wheels", response: array("WheelSpinHistoryResponse") }),
    },
    "/wheels/{wheelId}/reset-history": {
      post: operation({ id: "resetWheelHistory", tag: "Wheels", status: "204" }),
    },
    "/wheels/{wheelId}/members": {
      post: operation({ id: "addWheelMember", tag: "Wheels", request: "AddWheelMemberDto", response: ref("WheelMemberResponse"), status: "201" }),
    },
    "/wheels/{wheelId}/members/{memberUserId}": {
      patch: operation({ id: "updateWheelMember", tag: "Wheels", request: "UpdateWheelMemberDto", response: ref("WheelMemberResponse") }),
      delete: operation({ id: "removeWheelMember", tag: "Wheels", status: "204" }),
    },
    "/wheels/{wheelId}/items": {
      post: operation({ id: "addWheelItem", tag: "Wheels", request: "AddWheelItemDto", response: ref("WheelItemResponse"), status: "201" }),
    },
    "/wheels/{wheelId}/items/{itemId}": {
      patch: operation({ id: "updateWheelItem", tag: "Wheels", request: "UpdateWheelItemDto", response: ref("WheelItemResponse") }),
      delete: operation({ id: "deleteWheelItem", tag: "Wheels", status: "204" }),
    },
    "/wheels/{wheelId}/reorder": {
      post: operation({ id: "reorderWheelItems", tag: "Wheels", request: "ReorderWheelItemsDto", response: array("WheelItemResponse"), status: "201" }),
    },
    "/public/wheels/{publicSlug}": {
      get: operation({ id: "getPublicWheel", tag: "Wheels", response: ref("PublicWheelDetailsResponse"), anonymous: true }),
    },
    "/openapi.json": {
      get: {
        operationId: "getOpenApiContract",
        tags: ["Contract"],
        security: [],
        responses: { "200": { description: "This OpenAPI document" } },
      },
    },
  };

  for (const [path, pathItem] of Object.entries(paths)) {
    const parameters = [...path.matchAll(/\{([^}]+)\}/g)].map(
      ([, name]) => ({
        name,
        in: "path",
        required: true,
        schema: name === "tmdbId" ? { type: "integer" } : { type: "string" },
      }),
    );

    for (const value of Object.values(pathItem)) {
      if (parameters.length > 0) {
        value.parameters = parameters;
      }
    }
  }

  return paths;

  function resourcePaths({ base, tag, singular, createRequest, updateRequest, listResponse, detailsResponse }) {
    const parameter = singular === "Wheel" ? "wheelId" : "listId";
    return {
      [base]: {
        get: operation({ id: `list${singular}s`, tag, response: listResponse }),
        post: operation({ id: `create${singular}`, tag, request: createRequest, response: detailsResponse, status: "201" }),
      },
      [`${base}/{${parameter}}`]: {
        get: operation({ id: `get${singular}`, tag, response: detailsResponse }),
        patch: operation({ id: `update${singular}`, tag, request: updateRequest, response: detailsResponse }),
        delete: operation({ id: `delete${singular}`, tag, status: "204" }),
      },
    };
  }
}
